import { useI18n } from '../lib/i18n'

type TextLocale = 'zh' | 'en'

const TEXTS = {
  zh: {
    nav: {
      home: '首页',
      dashboard: '仪表盘',
      settings: '设置',
      ranking: '排行榜',
      team: '战队',
      friends: '好友',
      cards: 'Aime卡配置',
      setup: '配置指南',
      transfer: '数据迁移',
      collectibles: '收藏品',
      pictures: 'maimai相片',
      support: '社区',
      admin: '管理',
      language: '语言',
      logout: '退出登录',
    },
    common: {
      save: '保存',
      saved: '已保存',
      failed: '失败',
      loadingFailed: '加载失败',
      close: '关闭',
      empty: '—',
      error: '错误',
      requestFailed: '请求失败',
      working: '处理中…',
      previousPage: '上一页',
      nextPage: '下一页',
      yes: '是',
      no: '否',
      cancel: '取消',
      delete: '删除',
      edit: '编辑',
      create: '创建',
      add: '添加',
      search: '搜索',
      clear: '清除',
      submit: '提交',
      back: '返回',
      enabled: '启用',
      name: '名称',
      player: '玩家',
      member: '成员',
      members: '成员',
      leader: '队长',
      id: 'ID',
      level: '等级',
      rating: 'Rating',
      time: '时间',
      music: '乐曲',
      difficulty: '难度',
      achievement: '达成率',
      maxCombo: 'Max combo',
      ratingChange: 'Rating ±',
      prompt: '提示',
      musicWithId: (id: number | string) => `Music ${id}`,
      teamWithId: (id: number | string) => `Team ${id}`,
    },
    layout: {
      games: 'Games',
      darkMode: '深色模式',
      openMenu: '打开菜单',
    },
    support: {
      community: '社区与支持',
      noLinks: '未配置社区链接（.env）',
    },
    homePage: {
      noAvatar: '无头像',
      id: 'ID',
      level: '等级',
      rating: '评级',
      completion: '完成度',
      lastPlayed: (date: string) => `上次游玩： ${date}`,
      games: '游戏概要',
      inGameName: '游戏内名称',
      lastLogin: '最近登录',
      noGameData: '暂无游戏数据',
    },
    authPages: {
      login: '登录',
      register: '注册',
      username: '用户名',
      password: '密码',
      resetPassword: '重置密码',
      verifyEmail: '验证邮箱',
      submit: '提交',
      back: '返回',
      dividerOr: '或',
      passkeyLogin: '使用通行密钥登录',
      passkeyNoToken: '服务器未返回登录令牌',
      passkeyError: '通行密钥操作失败',
      oauthCallbackWorking: '正在完成登录…',
      oauthCallbackMissing: '缺少登录参数，将返回登录页。',
      oauthContinue: (name: string) => `使用 ${name} 继续`,
      oauthNotConfiguredHint: '需在后端配置该渠道的 client-id 后可用',
      oauthBindNeedToken: '请先登录后再绑定',
      loginFailed: '登录失败',
      turnstileRequired: 'VITE_TURNSTILE_SITE_KEY 未配置；生产环境必须配置 Turnstile。',
      turnstileMissing: 'VITE_TURNSTILE_SITE_KEY 未配置。',
      switchLightMode: '切换到浅色模式',
      switchDarkMode: '切换到深色模式',
      email: 'Email',
      resetMailSent: '若邮箱存在，您将收到重置邮件。',
      requestFailed: '请求失败',
      missingVerifyParams: '缺少验证参数',
      emailVerified: '邮箱已验证，请登录。',
      verifyFailed: '验证失败',
      missingToken: '缺少 token',
      unknownError: '未知错误',
      invalidTokenFormat: '无效的令牌格式',
      invalidResetLink: '无效的密码重置链接。',
      requestNewLink: '请求新链接',
      passwordUpdated: '密码已更新，请登录。',
    },
    notFound: {
      title: '页面不存在',
      backHome: '回首页',
    },
    maiPhoto: {
      error: '错误',
    },
    userProfile: {
      notFound: 'Not found',
      invalidUser: 'Invalid user',
      missingRivalId: '缺少好友标识',
      friendAdded: '已添加好友',
      friendRemoved: '已移除好友',
      friendChangedDesc: (name: string, add: boolean) => `${name} ${add ? '已加入列表' : '已从列表移除'}`,
      friendActionFailed: '好友操作失败',
      removeFriend: '移除好友',
      addFriend: '添加好友',
      removeRival: '移除劲敌',
      addRival: '添加劲敌',
      gameDataTitle: (game: string) => `${game} · 数据`,
    },
    gamesPage: {
      games: 'Games',
      overview: '概览',
      songs: '乐曲列表',
      plays: '游玩记录',
      noSummary: '该游戏暂无绑定数据或无法加载摘要',
      loadSongsFailed: '无法加载乐曲列表',
      loadMusicFailed: '无法加载曲库',
      loadPlaysFailed: '无法加载游玩记录',
      ratingTrend: 'Rating 趋势',
      playsHeatmap: '游玩热力图',
      team: '战队',
      leader: '队长',
      members: '成员',
      player: '玩家',
      previousPage: '上一页',
      nextPage: '下一页',
      summary: '概要',
      highestRating: '最高 Rating',
      playCount: 'PC数',
      serverRank: '服务器排名',
      romVersion: 'ROM版本',
      lastPlayed: '最近游玩',
      statsTitle: (name: string) => `${name} · 统计`,
      rankDistribution: '等级分布',
      recentScores: '最近成绩',
      noRecords: '暂无记录',
      noPlaylog: '无游玩记录',
      noCalendar: '暂无游玩日历数据',
      calendarHint: '最近一年 · 颜色越深游玩越多',
      ratingComposition: 'Rating 构成',
      level: '等级',
      ratingChangeShort: 'Rating ±',
      best30: 'Best 30',
      new20: 'New 20',
      recent10: 'Recent 10',
      best35: 'B35',
      best15: 'B15',
      page: (page: number) => `第 ${page + 1} 页`,
    },
    musicLibrary: {
      title: '乐曲列表',
      searchPlaceholder: '搜索歌曲 / 作曲 / ID',
      genreFilter: '分类筛选',
      allGenres: '全部分类',
      onlyPlayed: '只看有记录',
      playCount: (count: number) => `${count} 次游玩`,
      unknownComposer: '未知作曲',
      noMatches: '没有匹配的乐曲。',
      totalPlays: (count: number) => `总游玩 ${count}`,
      bestScore: '最好成绩',
      chartRating: '单曲 Rating',
      plays: '游玩次数',
      miss: 'Miss',
      justiceCritical: 'Justice C.',
      justice: 'Justice',
      attack: 'Attack',
      noRecord: '暂无记录',
      pickSong: '请选择左侧乐曲。',
    },
    playlogExplorer: {
      title: '游玩记录',
      searchPlaceholder: '搜索歌曲 / 时间 / ID',
      noMatches: '没有匹配的记录。',
      unknownComposer: '未知作曲',
      score: '成绩',
      rank: '段位',
      chartRating: '单曲 Rating',
      ratingDelta: '玩家 Rating 变化',
      time: '时间',
      track: 'Track',
      clear: '通关',
      freePlay: '免费曲',
      judgeCounts: '判定统计',
      laneRates: '各键型比率',
      newRecord: 'New Record',
      trackBadge: (track: number | string) => `Track ${track}`,
      judgeHeaven: 'Justice Heaven',
      judgeCritical: 'Justice Critical',
      justice: 'Justice',
      attack: 'Attack',
      missGuilty: 'Miss / Guilty',
      tap: 'Tap',
      hold: 'Hold',
      slide: 'Slide',
      air: 'Air',
      flick: 'Flick',
      pickPlay: '请选择左侧记录。',
    },
    trendChart: {
      insufficient: (days: number) => `最近 ${days} 天内可绘点不足，暂无趋势图（多打几把或稍后再试）`,
      ariaLabel: 'Rating 趋势',
      yAxis: '纵轴：Rating',
      xAxis: '横轴：日期',
    },
    collectibles: {
      unlockAll: '可选择全部收藏品',
      save: '保存',
      equipped: '当前选择',
      nothingUnlocked: '暂无已解锁收藏品',
      change: '更改',
      close: '关闭',
      searchLabel: '搜索名称或 ID',
      searchPlaceholder: '搜索…',
      works: '所属作品',
      worksFilter: '所属作品筛选',
      allWorks: '全部作品',
      illustrator: '画师',
      characterLevel: '角色等级',
      applyLevelAndSelect: '应用等级并选中',
      unlockAndSelect: '解锁并选中',
      ownedLevel: (level: number | string) => `已拥有 Lv.${level}`,
      locked: '未拥有',
      additionalImages: '追加立绘',
      rankRewards: 'Rank 奖励',
      noMatches: '没有匹配的收藏品。',
      unlocking: '解锁中…',
      lockedClickToUnlock: '未拥有，点击先解锁',
      characterUnlocked: (level: number) => `已解锁角色 Lv.${level}`,
      characterSelected: '已选择角色',
      characterUpdated: (level: number) => `已更新到 Lv.${level}`,
      saveToApply: '记得点击页面上的保存来应用角色。',
      characterUpdateFailed: '角色操作失败',
      unlockCharacterBeforeSave: '请先解锁该角色，再保存当前角色。',
      saveFailed: '保存失败',
      fieldLabels: {
        nameplateId: '名牌',
        frameId: '边框',
        characterId: '角色',
        trophyId: '称号',
        trophyIdSub1: '称号2',
        trophyIdSub2: '称号3',
        mapIconId: '地图图标',
        voiceId: '系统语音',
        stageId: '舞台',
        avatarWear: '企鹅服饰',
        avatarHead: '企鹅头饰',
        avatarFace: '企鹅面部',
        avatarSkin: '企鹅皮肤',
        avatarItem: '企鹅物品',
        avatarFront: '企鹅前景',
        avatarBack: '企鹅背景',
        userName: '游戏内名称',
      },
    },
    friendsPage: {
      addSection: '添加 CHUNITHM 好友',
      addHint: '这里填写 Aqua 用户名，不是游戏内昵称。',
      usernamePlaceholder: '输入 Aqua 用户名',
      add: '添加好友',
      adding: '添加中…',
      addSuccessTitle: '好友已添加',
      addSuccessDesc: (name: string) => `${name} 已加入好友列表`,
      addFailedTitle: '添加好友失败',
      addFailed: '添加失败',
      removeSuccessTitle: '好友已移除',
      removeSuccessDesc: (name: string) => `${name} 已从列表移除`,
      removeFailedTitle: '移除好友失败',
      removeFailed: '移除失败',
      favoriteAddedTitle: '已登录到喜爱',
      favoriteRemovedTitle: '已取消喜爱',
      favoriteDesc: (name: string, add: boolean) => `${name} ${add ? '现在会作为劲敌槽位返回给客户端' : '已从劲敌槽位移除'}`,
      favoriteFailedTitle: '喜爱设置失败',
      actionFailed: '操作失败',
      list: '好友列表',
      count: (count: number) => `共 ${count} 位好友`,
      favoriteCount: (count: number) => `已登录到喜爱 ${count} / 4。`,
      pinned: '喜爱中',
      level: (level: number | string) => `等级 ${level}`,
      working: '处理中…',
      unpin: '取消喜爱',
      pin: '登录到喜爱',
      removing: '移除中…',
      remove: '删除',
      rating: 'Rating',
      favoriteSlot: '喜爱槽位',
      best: '最高',
      team: '战队',
      id: 'ID',
      addedAt: '添加时间',
      empty: '还没有 CHUNITHM 好友，先加一个试试。',
    },
    teamPage: {
      requestFailed: '请求失败',
      enterTeamNameTitle: '请输入战队名称',
      enterTeamNameDesc: '战队名不能为空。',
      invalidEmblemTitle: '徽章 ID 无效',
      invalidEmblemDesc: '徽章 ID 需要是大于等于 0 的整数。',
      createdTitle: '战队已创建',
      createdDesc: (name: string, id: number) => `${name} 已创建，ID ${id}`,
      createFailed: '创建战队失败',
      updatedTitle: '战队资料已保存',
      updateFailed: '保存战队失败',
      joinRequestedTitle: '申请已提交',
      joinRequestedDesc: (name: string) => `已向 ${name} 提交申请。`,
      joinFailed: '提交申请失败',
      requestCancelledTitle: '申请已取消',
      cancelRequestFailed: '取消申请失败',
      approvedTitle: '已通过申请',
      approvedDesc: (name: string) => `${name} 已加入战队。`,
      approveFailed: '通过申请失败',
      rejectedTitle: '已拒绝申请',
      rejectedDesc: (name: string) => `${name} 的申请已拒绝。`,
      rejectFailed: '拒绝申请失败',
      leaveConfirm: '退出当前战队？',
      leftTitle: '已退出战队',
      leaveFailed: '退出战队失败',
      disbandConfirm: '解散当前战队？',
      disbandedTitle: '战队已解散',
      disbandedDesc: '所有成员都已被移出战队。',
      disbandFailed: '解散战队失败',
      currentTeam: '当前战队',
      leaderValue: (name: string) => `队长 ${name}`,
      totalExp: '总 EXP',
      myExp: '我的贡献',
      memberCount: '成员人数',
      rank: '战队排名',
      actions: '战队操作',
      teamName: '战队名称',
      teamColorRank: '战队等级（颜色，1是虹以此类推）',
      teamRank: '战队等级',
      saving: '保存中…',
      saveTeam: '保存战队资料',
      leaveTeam: '退出战队',
      disbandTeam: '解散战队',
      memberViewHint: (leader: string) => `当前队长是 ${leader}。普通成员只能查看资料和退出战队。`,
      joinRequests: '入队申请',
      pendingRequests: (count: number) => `${count} 条待审核`,
      noRequests: '目前没有新的入队申请。',
      memberList: '成员列表',
      membersCount: (count: number) => `${count} 人`,
      noMembers: '当前战队还没有成员数据。',
      createTeam: '创建战队',
      createHint: '输入战队名称后直接创建。系统会自动生成 100xxxx 的战队 ID，并让你成为队长。',
      optionalTeamRank: '战队等级（可选）',
      creating: '创建中…',
      joinTeam: '加入战队',
      joinHint: '输入战队 ID 提交申请。队长通过后，你才会真正加入战队。',
      teamId: '战队 ID',
      sending: '提交中…',
      sendRequest: '提交申请',
      pendingRequest: '当前有一条待审核申请',
      requestTime: (time: string) => `申请时间 ${time}`,
      cancelRequest: '取消申请',
      previewMeta: (members: number, rank: string) => `成员 ${members} 人 · 排名 ${rank}`,
      noTeam: '当前还没有加入任何战队。',
      leader: '队长',
      level: (level: number | string) => `等级 ${level}`,
      exp: (value: number | string) => `贡献 ${value}`,
      last: (time: string) => `最近 ${time}`,
      requested: (time: string) => `申请时间 ${time}`,
      approve: '通过',
      reject: '拒绝',
    },
    admin: {
      tabs: {
        overview: '概览',
        users: '用户',
        loginBonus: '登录奖励',
        unlock: '解锁挑战',
        downloadOrder: 'DownloadOrder',
      },
      checking: '检查管理员权限…',
      overviewTitle: '管理员控制台',
      loggedInAs: (name: string) => `已以管理员身份登录：${name}`,
      overviewHint: '使用顶部标签管理用户、CHUNITHM 登录奖励、解锁挑战与 ALL.Net DownloadOrder 配置。',
      userSearchPlaceholder: '搜索用户名或邮箱',
      displayName: '显示名',
      email: '邮箱',
      cards: '卡片数',
      detail: '详情',
      totalPages: (page: number, pages: number, total: number) => `${page} / ${pages}（共 ${total}）`,
      invalidUser: '无效用户',
      backToList: '返回列表',
      editUser: (id: number) => `编辑用户 #${id}`,
      country: '国家 (≤3)',
      region: '地区 (≤2)',
      place: '位置',
      bio: '简介',
      emailVerified: '邮箱已验证',
      rankingDisabled: '不参与排行榜',
      emailReadonly: (email: string | undefined) => `邮箱（只读）: ${email ?? ''}`,
      rankingBanned: '排行封禁',
      unbanRanking: '解除封禁',
      banRanking: '封禁排行',
      note: '注意',
      createPreset: '新建预设',
      presetList: '预设列表',
      entries: '条目',
      addEntry: '添加条目',
      days: '天数',
      deletePresetConfirm: '删除预设及其所有条目？',
      deleteEntryConfirm: '删除条目？',
      loginBonusNote:
        'CHUNITHM 客户端更稳的是吃游戏资源里原本就存在的签到 preset / entry ID。这里直接新建任意自定义签到，后端可以发奖，但客户端不一定会弹出签到内容。想让街机端稳定显示，最好复用游戏资源里已有的签到数据，或者给客户端补对应的 LoginBonus 资源。',
      optionalPresetId: '可选 presetId',
      repeatable: '可重复 (ID < 3000)',
      newEntryForPreset: (id: number) => `预设 ${id} — 新建条目`,
      newItem: '新建',
      editItem: (id: number) => `编辑 #${id}`,
      list: '列表',
      deleteUnlockConfirm: '删除该解锁挑战？',
      downloadOrder: {
        deleteIniConfirm: '删除这个 INI 和所有分配？',
        deleteAssignmentConfirm: '删除这个序列号分配？',
        newIni: '新建 opt INI',
        fileName: '文件名',
        title: '标题',
        optionalInstallUrls: 'OPTIONAL INSTALL URL，每行一个',
        preview: '预览',
        editIni: (id: number) => `编辑 INI #${id}`,
        iniList: 'INI 列表',
        file: '文件',
        game: '游戏',
        description: '描述',
        assignment: '序列号下发',
        clientVersion: '客户端版本 ver',
        select: '请选择',
        createAssignment: '创建分配',
        editAssignment: (id: number) => `编辑分配 #${id}`,
        assignmentList: '分配列表',
        downloadReports: '下载报告',
        type: '类型',
        status: '状态',
        progress: '进度',
      },
    },
    chusanTeamSettings: {
      invalidTeamId: 'teamId 必须是大于 0 的整数',
      invalidEmblem: 'emblemId 不能小于 0',
      saved: '队伍设置已保存',
      team: '战队',
      hint: '同一个 teamId 代表同一支战队。多个用户填写相同 teamId，就会共享战队名称、徽章和排名。',
      loading: '正在读取队伍数据…',
      currentTeam: '当前战队',
      teamExpRank: '战队总 EXP / 排名',
      members: (count: number) => `成员 ${count} 人`,
      myExpEmblem: '个人贡献 / 徽章',
      teamId: 'teamId',
      teamName: '战队名称',
      emblemId: '徽章 ID',
      save: '保存战队设置',
      ranking: '战队排行（Top 10）',
      emblem: (id: number) => `徽章 ${id}`,
      noData: '暂无战队数据',
    },
    settingsPage: {
      tabs: {
        profile: '资料',
        global: '全局游戏',
        chu3: 'CHUNITHM',
        mai2: 'maimaiDX',
        ongeki: '音击',
        wacca: 'WACCA',
      },
      loadingUser: '正在加载用户信息…',
      profile: {
        section: '个人资料',
        displayName: '显示名',
        bio: '简介',
        save: '保存',
        email: '邮箱',
        oauthSection: '已关联的第三方账号',
        oauthEmpty: '尚未关联任何账号。',
        passkeySection: '通行密钥（Passkey）',
        passkeyEmpty: '尚未注册通行密钥。',
      },
      global: {
        section: '地区',
      },
      auth: {
        oauthUnlink: '解除关联',
        oauthUnlinked: '已解除关联',
        passkeyAdd: '添加通行密钥',
        passkeyAdded: '已添加通行密钥',
        passkeyRemoved: '已移除通行密钥',
        passkeyRemove: '移除',
        passkeyError: '通行密钥操作失败',
      },
    },
    gameOptionFields: {
      empty: '（无此项服务器配置）',
      save: '保存',
    },
    globalSettings: {
      webHint: '以下选项主要影响网页上的分数与图表显示；机台连接方式请参见配置指南。',
      regionHint: '地区用于排行榜等区域相关功能。',
      prefecture: '都道府县',
      syncHint: '更改后立即同步到账户。',
      select: '请选择…',
      profileOptions: '账户级选项',
    },
    segaUsernameEditor: {
      placeholder: '输入 8 个以内全角字符',
      save: '保存',
      helper: (length: number, max: number) =>
        `自动转为全角字符，可用特殊符号如下。${length}/${max}`,
    },
    chu3Appearance: {
      section: 'CHUNITHM 游戏内名称',
      renameAction: '改名',
    },
    mai2Extra: {
      inGameName: '游戏内名称',
      renameAction: '改名',
      exportSave: '导出 maimai 存档 (JSON)',
    },
    ongekiExtra: {
      inGameName: '游戏内名称',
      renameAction: '改名',
    },
    chusanExtra: {
      basics: 'CHUNITHM 基础',
      loginRewards: '登录奖励',
      team: '战队',
      openTeamPage: '前往战队页',
      matching: '全国对战 & Linked Verse',
      choosePreset: '选择对战服预设…',
      customMatchingServer: '自定义对战服务器',
      symbolChat: '对战快捷表情',
      symbolChatSlot: (slot: number) => `快捷表情 #${slot}`,
      defaultOption: '（默认）',
      openCollectibles: '前往收藏品页面设置 →',
      importExport: '导入 / 导出',
      importBusy: '导入中…',
      importSave: '导入存档',
      exportSave: '导出存档',
      lastFile: (name: string) => `最近选择：${name}`,
      importSuccessTitle: '导入成功',
      importSuccessDesc: 'CHUNITHM 存档已导入。',
      importFailedTitle: '导入失败',
      matchingDialogTitle: '选择对战服',
      guide: '教程',
      custom: '自定义',
      customHint: '手动填写 URL（见下方字段）。',
    },
    chusanLoginRewards: {
      none: '无',
      ticket: '票券',
      save: '保存登录奖励',
      ticketOptions: [
        { itemKind: 5, itemId: 110, label: 'CHUNITHM-NET 标准票' },
        { itemKind: 5, itemId: 302, label: '角色 EXP x3.0 票' },
        { itemKind: 5, itemId: 312, label: '角色 EXP x6.0 票' },
        { itemKind: 5, itemId: 313, label: '角色 EXP x9.0 票' },
        { itemKind: 5, itemId: 314, label: '角色 EXP x12.0 票' },
        { itemKind: 5, itemId: 320, label: '角色 EXP 储存票' },
        { itemKind: 5, itemId: 321, label: '角色 EXP 储存票（赠送）' },
        { itemKind: 5, itemId: 402, label: 'MASTER 游玩票' },
        { itemKind: 5, itemId: 601, label: 'ULTIMA 游玩票' },
        { itemKind: 5, itemId: 701, label: "WORLD'S END 游玩票" },
        { itemKind: 5, itemId: 2020, label: '地图进度 x2（高级）' },
        { itemKind: 5, itemId: 2040, label: '地图进度 x3（高级）' },
        { itemKind: 5, itemId: 2060, label: '地图进度 x4（高级）' },
        { itemKind: 5, itemId: 3060, label: '角色 EXP x6.0 票（高级）' },
        { itemKind: 5, itemId: 3090, label: '角色 EXP x9.0 票（高级）' },
        { itemKind: 5, itemId: 3120, label: '角色 EXP x12.0 票（高级）' },
        { itemKind: 5, itemId: 5020, label: '地图进度 x2（礼物）' },
        { itemKind: 5, itemId: 5040, label: '地图进度 x3（礼物）' },
        { itemKind: 5, itemId: 5060, label: '地图进度 x4（礼物）' },
        { itemKind: 5, itemId: 5510, label: 'SPECIAL 票（当日限定）' },
      ],
    },
    setup: {
      connectionAddress: '连接地址',
      connectionEnvHint: '请在环境变量配置 VITE_AQUA_CONNECTION（机台填写的 DNS / URL）',
      iniExample: 'segatools.ini 示例',
      iniHint:
        '以下为参考原版 AquaNet 的示例片段：`[dns]` 与 `[keychip]` 会填入上方连接地址与当前账号 keychip；其余分节为常见占位，请按你实际工具与服主说明修改。',
      copyAll: '复制全部',
      keychip: 'Keychip',
      keychipHint: '每个账号一个 keychip，用于机台识别。勿分享给他人。',
      notAllocated: '尚未分配',
      allocate: '分配Keychip',
      allocateSuccessTitle: 'Keychip 已就绪',
      allocateSuccessDesc: '已分配新的 keychip，旧编号已失效；可直接复制下方 segatools 示例。',
      allocateFailedTitle: '分配失败',
      dnsPlaceholder: 'https://你的服务器地址',
    },
    transfer: {
      serverParams: '源服务器 / 目标服务器参数',
      serverParamsHint:
        'dns 为机台可访问的 AquaDX URL；card 为卡号；keychip、game、version 与 ALL.Net 配置一致。',
      dns: 'DNS (URL)',
      card: 'Card',
      keychip: 'Keychip',
      gameCode: 'Game code',
      version: 'Version',
      testConnection: '检测连接',
      pullExport: '拉取导出 (SSE)',
      pushJson: '推送 JSON',
      logs: '日志',
      exportData: '导出数据 / 手动粘贴推送',
      exportPlaceholder: 'pull 成功后自动填入，或可粘贴 JSON',
      connectionSuccess: '连接检测成功',
      pushDone: '推送完成',
    },
    linkCard: {
      summary: '概要',
      bindCard: '绑定新的Aime卡',
      accessCode: 'Access Code',
      accessCodePlaceholder: '1234 5678 9012 3456 7890',
      bind: '绑定',
      linkedCards: '已绑定卡片',
      noCards: '暂无卡片',
      cardNumber: '卡号',
      status: '状态',
      action: '操作',
      linked: '已关联',
      rankingBanned: '排行封禁',
      unlink: '解绑',
      bindSuccess: '绑卡成功',
      unlinkSuccess: '已解绑',
      rating: 'Rating',
      ghost: 'Ghost',
    },
  },
  en: {
    nav: {
      home: 'Home',
      dashboard: 'Dashboard',
      settings: 'Settings',
      ranking: 'Ranking',
      team: 'Team',
      friends: 'Friends',
      cards: 'Cards',
      setup: 'Setup',
      transfer: 'Transfer',
      collectibles: 'Collectibles',
      pictures: 'maimai Photos',
      support: 'Community',
      admin: 'Admin',
      language: 'Language',
      logout: 'Log out',
    },
    common: {
      save: 'Save',
      saved: 'Saved',
      failed: 'Failed',
      loadingFailed: 'Load failed',
      close: 'Close',
      empty: '—',
      error: 'Error',
      requestFailed: 'Request failed',
      working: 'Working…',
      previousPage: 'Previous',
      nextPage: 'Next',
      yes: 'Yes',
      no: 'No',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      create: 'Create',
      add: 'Add',
      search: 'Search',
      clear: 'Clear',
      submit: 'Submit',
      back: 'Back',
      enabled: 'Enabled',
      name: 'Name',
      player: 'Player',
      member: 'Member',
      members: 'Members',
      leader: 'Leader',
      id: 'ID',
      level: 'Level',
      rating: 'Rating',
      time: 'Time',
      music: 'Song',
      difficulty: 'Difficulty',
      achievement: 'Achievement',
      maxCombo: 'Max combo',
      ratingChange: 'Rating ±',
      prompt: 'Notice',
      musicWithId: (id: number | string) => `Music ${id}`,
      teamWithId: (id: number | string) => `Team ${id}`,
    },
    layout: {
      games: 'Games',
      darkMode: 'Dark mode',
      openMenu: 'Open menu',
    },
    support: {
      community: 'Community & support',
      noLinks: 'No community links configured (.env)',
    },
    homePage: {
      noAvatar: 'No avatar',
      id: 'ID',
      level: 'Level',
      rating: 'Rating',
      completion: 'Completion',
      lastPlayed: (date: string) => `Last played: ${date}`,
      games: 'Games',
      inGameName: 'Name',
      lastLogin: 'Last login',
      noGameData: 'No game data yet',
    },
    authPages: {
      login: 'Log in',
      register: 'Register',
      username: 'Username',
      password: 'Password',
      resetPassword: 'Reset password',
      verifyEmail: 'Verify email',
      submit: 'Submit',
      back: 'Back',
      dividerOr: 'or',
      passkeyLogin: 'Sign in with passkey',
      passkeyNoToken: 'Server did not return a login token',
      passkeyError: 'Passkey action failed',
      oauthCallbackWorking: 'Completing sign-in…',
      oauthCallbackMissing: 'Missing sign-in parameters. Redirecting to login.',
      oauthContinue: (name: string) => `Continue with ${name}`,
      oauthNotConfiguredHint: 'Enable by configuring OAuth client IDs on the server',
      oauthBindNeedToken: 'Sign in first to link an account',
      loginFailed: 'Login failed',
      turnstileRequired: 'VITE_TURNSTILE_SITE_KEY is not configured; production must configure Turnstile.',
      turnstileMissing: 'VITE_TURNSTILE_SITE_KEY is not configured.',
      switchLightMode: 'Switch to light mode',
      switchDarkMode: 'Switch to dark mode',
      email: 'Email',
      resetMailSent: 'If the email exists, you will receive a reset email.',
      requestFailed: 'Request failed',
      missingVerifyParams: 'Missing verification parameters',
      emailVerified: 'Email verified. Please sign in.',
      verifyFailed: 'Verification failed',
      missingToken: 'Missing token',
      unknownError: 'Unknown error',
      invalidTokenFormat: 'Invalid token format',
      invalidResetLink: 'Invalid password reset link.',
      requestNewLink: 'Request a new link',
      passwordUpdated: 'Password updated. Please sign in.',
    },
    notFound: {
      title: 'Page not found',
      backHome: 'Back home',
    },
    maiPhoto: {
      error: 'Error',
    },
    userProfile: {
      notFound: 'Not found',
      invalidUser: 'Invalid user',
      missingRivalId: 'Missing rival id',
      friendAdded: 'Friend added',
      friendRemoved: 'Friend removed',
      friendChangedDesc: (name: string, add: boolean) => `${name} ${add ? 'was added' : 'was removed'}`,
      friendActionFailed: 'Friend action failed',
      removeFriend: 'Remove friend',
      addFriend: 'Add friend',
      removeRival: 'Remove rival',
      addRival: 'Add rival',
      gameDataTitle: (game: string) => `${game} · Data`,
    },
    gamesPage: {
      games: 'Games',
      overview: 'Overview',
      songs: 'Songs',
      plays: 'Plays',
      noSummary: 'No bound data for this game, or summary failed to load',
      loadSongsFailed: 'Failed to load song list',
      loadMusicFailed: 'Failed to load music database',
      loadPlaysFailed: 'Failed to load play records',
      ratingTrend: 'Rating trend',
      playsHeatmap: 'Plays heatmap',
      team: 'Team',
      leader: 'Leader',
      members: 'Members',
      player: 'Player',
      previousPage: 'Previous',
      nextPage: 'Next',
      summary: 'Summary',
      highestRating: 'Highest Rating',
      playCount: 'Plays',
      serverRank: 'Server rank',
      romVersion: 'ROM version',
      lastPlayed: 'Last played',
      statsTitle: (name: string) => `${name} · Stats`,
      rankDistribution: 'Rank distribution',
      recentScores: 'Recent scores',
      noRecords: 'No records',
      noPlaylog: 'No play records',
      noCalendar: 'No play calendar data',
      calendarHint: 'Last year · darker means more plays',
      ratingComposition: 'Rating composition',
      level: 'Level',
      ratingChangeShort: 'Rating ±',
      best30: 'Best 30',
      new20: 'New 20',
      recent10: 'Recent 10',
      best35: 'B35',
      best15: 'Best 15',
      page: (page: number) => `Page ${page + 1}`,
    },
    musicLibrary: {
      title: 'Song list',
      searchPlaceholder: 'Search song / composer / ID',
      genreFilter: 'Genre filter',
      allGenres: 'All genres',
      onlyPlayed: 'Only played',
      playCount: (count: number) => `${count} plays`,
      unknownComposer: 'Unknown composer',
      noMatches: 'No songs matched.',
      totalPlays: (count: number) => `Total plays ${count}`,
      bestScore: 'Best score',
      chartRating: 'Chart rating',
      plays: 'Plays',
      miss: 'Miss',
      justiceCritical: 'Justice C.',
      justice: 'Justice',
      attack: 'Attack',
      noRecord: 'No record',
      pickSong: 'Pick a song from the list.',
    },
    playlogExplorer: {
      title: 'Play history',
      searchPlaceholder: 'Search song / time / ID',
      noMatches: 'No records matched.',
      unknownComposer: 'Unknown composer',
      score: 'Score',
      rank: 'Rank',
      chartRating: 'Chart rating',
      ratingDelta: 'Player rating delta',
      time: 'Time',
      track: 'Track',
      clear: 'Clear',
      freePlay: 'Free play',
      judgeCounts: 'Judge counts',
      laneRates: 'Lane rates',
      newRecord: 'New Record',
      trackBadge: (track: number | string) => `Track ${track}`,
      judgeHeaven: 'Justice Heaven',
      judgeCritical: 'Justice Critical',
      justice: 'Justice',
      attack: 'Attack',
      missGuilty: 'Miss / Guilty',
      tap: 'Tap',
      hold: 'Hold',
      slide: 'Slide',
      air: 'Air',
      flick: 'Flick',
      pickPlay: 'Pick a play from the list.',
    },
    trendChart: {
      insufficient: (days: number) => `Not enough points in the last ${days} days. Play more or try again later.`,
      ariaLabel: 'Rating trend',
      yAxis: 'Y axis: Rating',
      xAxis: 'X axis: Date',
    },
    collectibles: {
      unlockAll: 'Unlock all collectibles',
      save: 'Save',
      equipped: 'Equipped',
      nothingUnlocked: 'Nothing unlocked',
      change: 'Change',
      close: 'Close',
      searchLabel: 'Search name or ID',
      searchPlaceholder: 'Search…',
      works: 'Works',
      worksFilter: 'Works filter',
      allWorks: 'All works',
      illustrator: 'Illustrator',
      characterLevel: 'Character level',
      applyLevelAndSelect: 'Apply level and select',
      unlockAndSelect: 'Unlock and select',
      ownedLevel: (level: number | string) => `Owned Lv.${level}`,
      locked: 'Locked',
      additionalImages: 'Additional images',
      rankRewards: 'Rank rewards',
      noMatches: 'No matches.',
      unlocking: 'Unlocking…',
      lockedClickToUnlock: 'Locked, click to unlock',
      characterUnlocked: (level: number) => `Character unlocked at Lv.${level}`,
      characterSelected: 'Character selected',
      characterUpdated: (level: number) => `Character updated to Lv.${level}`,
      saveToApply: 'Click Save on the page to equip it.',
      characterUpdateFailed: 'Character update failed',
      unlockCharacterBeforeSave: 'Unlock this character before saving it.',
      saveFailed: 'Save failed',
      fieldLabels: {
        nameplateId: 'Name plate',
        frameId: 'Frame',
        characterId: 'Character',
        trophyId: 'Title',
        trophyIdSub1: 'Title 2',
        trophyIdSub2: 'Title 3',
        mapIconId: 'Map icon',
        voiceId: 'System voice',
        stageId: 'Stage',
        avatarWear: 'Avatar outfit',
        avatarHead: 'Avatar head',
        avatarFace: 'Avatar face',
        avatarSkin: 'Avatar skin',
        avatarItem: 'Avatar item',
        avatarFront: 'Avatar front',
        avatarBack: 'Avatar back',
        userName: 'In-game name',
      },
    },
    friendsPage: {
      addSection: 'Add CHUNITHM friend',
      addHint: 'Use Aqua username here, not the in-game display name.',
      usernamePlaceholder: 'Enter Aqua username',
      add: 'Add friend',
      adding: 'Adding…',
      addSuccessTitle: 'Friend added',
      addSuccessDesc: (name: string) => `${name} was added`,
      addFailedTitle: 'Add friend failed',
      addFailed: 'Request failed',
      removeSuccessTitle: 'Friend removed',
      removeSuccessDesc: (name: string) => `${name} was removed`,
      removeFailedTitle: 'Remove friend failed',
      removeFailed: 'Request failed',
      favoriteAddedTitle: 'Pinned to favorites',
      favoriteRemovedTitle: 'Removed from favorites',
      favoriteDesc: (name: string, add: boolean) => `${name} ${add ? 'is now in rival favorites' : 'was removed from rival favorites'}`,
      favoriteFailedTitle: 'Favorite action failed',
      actionFailed: 'Request failed',
      list: 'Friend list',
      count: (count: number) => `${count} friends`,
      favoriteCount: (count: number) => `${count} / 4 pinned.`,
      pinned: 'Pinned',
      level: (level: number | string) => `Level ${level}`,
      working: 'Working…',
      unpin: 'Unpin',
      pin: 'Pin as rival',
      removing: 'Removing…',
      remove: 'Remove',
      rating: 'Rating',
      favoriteSlot: 'Favorite slot',
      best: 'Best',
      team: 'Team',
      id: 'ID',
      addedAt: 'Added at',
      empty: 'No CHUNITHM friends yet. Add one to start.',
    },
    teamPage: {
      requestFailed: 'Request failed',
      enterTeamNameTitle: 'Enter a team name',
      enterTeamNameDesc: 'Team name is required.',
      invalidEmblemTitle: 'Invalid emblem id',
      invalidEmblemDesc: 'Emblem id must be an integer >= 0.',
      createdTitle: 'Team created',
      createdDesc: (name: string, id: number) => `${name} was created, id ${id}`,
      createFailed: 'Create team failed',
      updatedTitle: 'Team saved',
      updateFailed: 'Save team failed',
      joinRequestedTitle: 'Request sent',
      joinRequestedDesc: (name: string) => `Request sent to ${name}.`,
      joinFailed: 'Send request failed',
      requestCancelledTitle: 'Request cancelled',
      cancelRequestFailed: 'Cancel request failed',
      approvedTitle: 'Request approved',
      approvedDesc: (name: string) => `${name} joined the team.`,
      approveFailed: 'Approve request failed',
      rejectedTitle: 'Request rejected',
      rejectedDesc: (name: string) => `${name}'s request was rejected.`,
      rejectFailed: 'Reject request failed',
      leaveConfirm: 'Leave this team?',
      leftTitle: 'Left team',
      leaveFailed: 'Leave team failed',
      disbandConfirm: 'Disband this team?',
      disbandedTitle: 'Team disbanded',
      disbandedDesc: 'All members were removed from the team.',
      disbandFailed: 'Disband team failed',
      currentTeam: 'Current team',
      leaderValue: (name: string) => `Leader ${name}`,
      totalExp: 'Team EXP',
      myExp: 'My EXP',
      memberCount: 'Members',
      rank: 'Rank',
      actions: 'Team actions',
      teamName: 'Team name',
      teamColorRank: 'Team color rank',
      teamRank: 'Team rank',
      saving: 'Saving…',
      saveTeam: 'Save team',
      leaveTeam: 'Leave team',
      disbandTeam: 'Disband team',
      memberViewHint: (leader: string) => `Current leader is ${leader}. Regular members can only view details and leave the team.`,
      joinRequests: 'Join requests',
      pendingRequests: (count: number) => `${count} pending`,
      noRequests: 'No join requests right now.',
      memberList: 'Members',
      membersCount: (count: number) => `${count} members`,
      noMembers: 'No team members yet.',
      createTeam: 'Create team',
      createHint: 'Enter a team name to create it. The system creates a 100xxxx team ID and makes you the leader.',
      optionalTeamRank: 'Team rank',
      creating: 'Creating…',
      joinTeam: 'Join team',
      joinHint: 'Enter a team ID to send a request. You join only after the leader approves.',
      teamId: 'Team ID',
      sending: 'Sending…',
      sendRequest: 'Send request',
      pendingRequest: 'Current pending request',
      requestTime: (time: string) => `Requested ${time}`,
      cancelRequest: 'Cancel request',
      previewMeta: (members: number, rank: string) => `${members} members · rank ${rank}`,
      noTeam: 'You are not in any team right now.',
      leader: 'Leader',
      level: (level: number | string) => `Level ${level}`,
      exp: (value: number | string) => `EXP ${value}`,
      last: (time: string) => `Last ${time}`,
      requested: (time: string) => `Requested ${time}`,
      approve: 'Approve',
      reject: 'Reject',
    },
    admin: {
      tabs: {
        overview: 'Overview',
        users: 'Users',
        loginBonus: 'Login rewards',
        unlock: 'Unlock challenge',
        downloadOrder: 'DownloadOrder',
      },
      checking: 'Checking admin permissions…',
      overviewTitle: 'Admin console',
      loggedInAs: (name: string) => `Logged in as admin: ${name}`,
      overviewHint: 'Use the top tabs to manage users, CHUNITHM login rewards, unlock challenges, and ALL.Net DownloadOrder configuration.',
      userSearchPlaceholder: 'Search username or email',
      displayName: 'Display name',
      email: 'Email',
      cards: 'Cards',
      detail: 'Details',
      totalPages: (page: number, pages: number, total: number) => `${page} / ${pages} (${total} total)`,
      invalidUser: 'Invalid user',
      backToList: 'Back to list',
      editUser: (id: number) => `Edit user #${id}`,
      country: 'Country (≤3)',
      region: 'Region (≤2)',
      place: 'Place',
      bio: 'Bio',
      emailVerified: 'Email verified',
      rankingDisabled: 'Exclude from ranking',
      emailReadonly: (email: string | undefined) => `Email (read-only): ${email ?? ''}`,
      rankingBanned: 'Ranking banned',
      unbanRanking: 'Unban ranking',
      banRanking: 'Ban ranking',
      note: 'Notice',
      createPreset: 'Create preset',
      presetList: 'Presets',
      entries: 'Entries',
      addEntry: 'Add entry',
      days: 'Days',
      deletePresetConfirm: 'Delete this preset and all entries?',
      deleteEntryConfirm: 'Delete this entry?',
      loginBonusNote:
        'CHUNITHM clients are more stable when using login bonus preset / entry IDs that already exist in game resources. Custom login bonuses can grant rewards from the backend, but may not appear on the client. For stable cabinet display, reuse login bonus data from game resources or add matching LoginBonus resources to the client.',
      optionalPresetId: 'Optional presetId',
      repeatable: 'Repeatable (ID < 3000)',
      newEntryForPreset: (id: number) => `Preset ${id} — new entry`,
      newItem: 'New',
      editItem: (id: number) => `Edit #${id}`,
      list: 'List',
      deleteUnlockConfirm: 'Delete this unlock challenge?',
      downloadOrder: {
        deleteIniConfirm: 'Delete this INI and all assignments?',
        deleteAssignmentConfirm: 'Delete this serial assignment?',
        newIni: 'New opt INI',
        fileName: 'File name',
        title: 'Title',
        optionalInstallUrls: 'OPTIONAL INSTALL URL, one per line',
        preview: 'Preview',
        editIni: (id: number) => `Edit INI #${id}`,
        iniList: 'INI list',
        file: 'File',
        game: 'Game',
        description: 'Description',
        assignment: 'Serial delivery',
        clientVersion: 'Client version ver',
        select: 'Select',
        createAssignment: 'Create assignment',
        editAssignment: (id: number) => `Edit assignment #${id}`,
        assignmentList: 'Assignment list',
        downloadReports: 'Download reports',
        type: 'Type',
        status: 'Status',
        progress: 'Progress',
      },
    },
    chusanTeamSettings: {
      invalidTeamId: 'teamId must be a positive integer',
      invalidEmblem: 'emblemId must be >= 0',
      saved: 'Team settings saved',
      team: 'Team',
      hint: 'The same teamId means the same team. Multiple users with the same teamId share team name, emblem, and ranking.',
      loading: 'Loading team data…',
      currentTeam: 'Current team',
      teamExpRank: 'Team EXP / Rank',
      members: (count: number) => `${count} members`,
      myExpEmblem: 'My EXP / Emblem',
      teamId: 'teamId',
      teamName: 'Team name',
      emblemId: 'Emblem ID',
      save: 'Save team settings',
      ranking: 'Team ranking (Top 10)',
      emblem: (id: number) => `Emblem ${id}`,
      noData: 'No team data yet',
    },
    settingsPage: {
      tabs: {
        profile: 'Profile',
        global: 'Global',
        chu3: 'CHUNITHM',
        mai2: 'maimaiDX',
        ongeki: 'Ongeki',
        wacca: 'WACCA',
      },
      loadingUser: 'Loading user…',
      profile: {
        section: 'Profile',
        displayName: 'Display name',
        bio: 'Bio',
        save: 'Save',
        email: 'Email',
        oauthSection: 'Linked accounts',
        oauthEmpty: 'No linked accounts yet.',
        passkeySection: 'Passkeys',
        passkeyEmpty: 'No passkeys yet.',
      },
      global: {
        section: 'Global & region',
      },
      auth: {
        oauthUnlink: 'Unlink',
        oauthUnlinked: 'Account unlinked',
        passkeyAdd: 'Add passkey',
        passkeyAdded: 'Passkey added',
        passkeyRemoved: 'Passkey removed',
        passkeyRemove: 'Remove',
        passkeyError: 'Passkey action failed',
      },
    },
    gameOptionFields: {
      empty: '(No server option available)',
      save: 'Save',
    },
    globalSettings: {
      webHint: 'These options mainly affect score display on the web; see setup for cab connection.',
      regionHint: 'Region is used for regional leaderboard features.',
      prefecture: 'Prefecture',
      syncHint: 'Saved to your account when changed.',
      select: 'Select…',
      profileOptions: 'Profile options',
    },
    segaUsernameEditor: {
      placeholder: 'Up to 8 full-width characters',
      save: 'Save',
      helper: (length: number, max: number) =>
        `Typed ASCII is converted to full-width automatically. Special symbols below. ${length}/${max}`,
    },
    chu3Appearance: {
      section: 'CHUNITHM in-game name',
      renameAction: 'Rename',
    },
    mai2Extra: {
      inGameName: 'In-game name',
      renameAction: 'Rename',
      exportSave: 'Export maimai save (JSON)',
    },
    ongekiExtra: {
      inGameName: 'In-game name',
      renameAction: 'Rename',
    },
    chusanExtra: {
      basics: 'CHUNITHM basics',
      loginRewards: 'Login rewards',
      team: 'Team',
      openTeamPage: 'Open team page',
      matching: 'National matching & Linked Verse',
      choosePreset: 'Choose matching preset…',
      customMatchingServer: 'Custom matching server',
      symbolChat: 'Symbol chat',
      symbolChatSlot: (slot: number) => `Symbol chat #${slot}`,
      defaultOption: '(default)',
      openCollectibles: 'Open Collectibles page →',
      importExport: 'Import / Export',
      importBusy: 'Importing…',
      importSave: 'Import CHUNITHM save',
      exportSave: 'Export CHUNITHM',
      lastFile: (name: string) => `Last file: ${name}`,
      importSuccessTitle: 'Import completed',
      importSuccessDesc: 'CHUNITHM save imported.',
      importFailedTitle: 'Import failed',
      matchingDialogTitle: 'Matching server',
      guide: 'Guide',
      custom: 'Custom',
      customHint: 'Enter URLs manually below.',
    },
    chusanLoginRewards: {
      none: 'None',
      ticket: 'Ticket',
      save: 'Save login rewards',
      ticketOptions: [
        { itemKind: 5, itemId: 110, label: 'CHUNITHM-NET Standard Ticket' },
        { itemKind: 5, itemId: 302, label: 'Character EXP x3.0 Ticket' },
        { itemKind: 5, itemId: 312, label: 'Character EXP x6.0 Ticket' },
        { itemKind: 5, itemId: 313, label: 'Character EXP x9.0 Ticket' },
        { itemKind: 5, itemId: 314, label: 'Character EXP x12.0 Ticket' },
        { itemKind: 5, itemId: 320, label: 'Character EXP Stock Ticket' },
        { itemKind: 5, itemId: 321, label: 'Character EXP Stock Ticket (Gift)' },
        { itemKind: 5, itemId: 402, label: 'MASTER Play Ticket' },
        { itemKind: 5, itemId: 601, label: 'ULTIMA Play Ticket' },
        { itemKind: 5, itemId: 701, label: "WORLD'S END Play Ticket" },
        { itemKind: 5, itemId: 2020, label: 'Map Progress x2 (Premium)' },
        { itemKind: 5, itemId: 2040, label: 'Map Progress x3 (Premium)' },
        { itemKind: 5, itemId: 2060, label: 'Map Progress x4 (Premium)' },
        { itemKind: 5, itemId: 3060, label: 'Character EXP x6.0 Ticket (Premium)' },
        { itemKind: 5, itemId: 3090, label: 'Character EXP x9.0 Ticket (Premium)' },
        { itemKind: 5, itemId: 3120, label: 'Character EXP x12.0 Ticket (Premium)' },
        { itemKind: 5, itemId: 5020, label: 'Map Progress x2 (Gift)' },
        { itemKind: 5, itemId: 5040, label: 'Map Progress x3 (Gift)' },
        { itemKind: 5, itemId: 5060, label: 'Map Progress x4 (Gift)' },
        { itemKind: 5, itemId: 5510, label: 'SPECIAL Ticket (Day Only)' },
      ],
    },
    setup: {
      connectionAddress: 'Connection',
      connectionEnvHint: 'Set VITE_AQUA_CONNECTION in env (the DNS / URL your cab uses).',
      iniExample: 'segatools.ini example',
      iniHint:
        'This sample follows original AquaNet. `[dns]` and `[keychip]` use the address above and your current account keychip; adjust the rest for your tooling and server instructions.',
      copyAll: 'Copy all',
      keychip: 'Keychip',
      keychipHint: 'Each account gets one keychip for cab identification. Do not share it.',
      notAllocated: 'Not allocated',
      allocate: 'Allocate keychip',
      allocateSuccessTitle: 'Keychip ready',
      allocateSuccessDesc: 'A new keychip is ready. The old one has been revoked; copy the segatools example below.',
      allocateFailedTitle: 'Allocation failed',
      dnsPlaceholder: 'https://your-server-address',
    },
    transfer: {
      serverParams: 'Source / target server settings',
      serverParamsHint:
        'dns is the AquaDX URL reachable by the cab; card is the access code; keychip, game, and version must match your ALL.Net setup.',
      dns: 'DNS (URL)',
      card: 'Card',
      keychip: 'Keychip',
      gameCode: 'Game code',
      version: 'Version',
      testConnection: 'Check connection',
      pullExport: 'Pull export (SSE)',
      pushJson: 'Push JSON',
      logs: 'Logs',
      exportData: 'Export data / manual JSON push',
      exportPlaceholder: 'Filled after pull succeeds, or paste JSON manually',
      connectionSuccess: 'Connection check succeeded',
      pushDone: 'Push completed',
    },
    linkCard: {
      summary: 'Summary',
      bindCard: 'Link a new Aime card',
      accessCode: 'Access Code',
      accessCodePlaceholder: '1234 5678 9012 3456 7890',
      bind: 'Link',
      linkedCards: 'Linked cards',
      noCards: 'No cards yet',
      cardNumber: 'Card',
      status: 'Status',
      action: 'Action',
      linked: 'Linked',
      rankingBanned: 'Ranking banned',
      unlink: 'Unlink',
      bindSuccess: 'Card linked',
      unlinkSuccess: 'Card unlinked',
      rating: 'Rating',
      ghost: 'Ghost',
    },
  },
}

export type AppTexts = (typeof TEXTS)['zh']

export function getAppTexts(locale: string): AppTexts {
  const resolved: TextLocale = locale === 'en' ? 'en' : 'zh'
  return TEXTS[resolved]
}

export function useAppTexts() {
  const { locale } = useI18n()
  return getAppTexts(locale)
}
